ENH: Disallow empty keys by default but support explicit enabling via --allow-empty-key|-E

diff --git a/bin/picoDB b/bin/picoDB
--- a/bin/picoDB
+++ b/bin/picoDB
@@ -22,7 +22,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--basedir DIR|--base-type config|data|runtime|cache|temp] [-n|--namespace NAMESPACE] -t|--table TABLE [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--basedir DIR|--base-type config|data|runtime|cache|temp] [-n|--namespace NAMESPACE] -t|--table TABLE [-E|--allow-empty-key] [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -a|--add|-u|--update KEY [...]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -d|--delete KEY'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -C|--truncate'
@@ -59,6 +59,8 @@ HELPDESCRIPTION
 				use. Determines the configuration directory.
     --table|-t TABLE		Category in the context of the application.
 				Determines the configuration file.
+    --allow-empty-key|-E	Allow empty KEY; note that these cannot be
+				returned via --get-as-dictionary.
     --add|-a|--update|-u KEY	Record KEY. An existing record is overwritten,
 				else it is appended.
     --delete|-d KEY		Delete any existing KEY record. When this is the
@@ -97,6 +99,9 @@ checkKeyArg()
     if [ $# -eq 0 ]; then
 	echo >&2 'ERROR: Need KEY argument.'
 	exit 2
+    elif [ -z "$1" ] && [ ! "$isAllowEmptyKey" ]; then
+	echo >&2 'ERROR: Empty KEY not allowed.'
+	exit 2
     fi
 }
 literalPattern()
@@ -122,6 +127,7 @@ multipleActionsError()
 }
 namespace=
 table=
+isAllowEmptyKey=
 key=
 typeset -a keys=()
 value=
@@ -160,6 +166,8 @@ do
 			    exit 2
 			fi >&2
 			;;
+	--allow-empty-key|-E)
+			shift; isAllowEmptyKey=t;;
 	--add|-a|--update|-u)
 			shift; [ -n "$action" -a "$action" != 'update' ] && multipleActionsError "$0"; action='update'
 			checkKeyArg "$@"
